=== BogdanDubrovniy/shop/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:tns="http://entities"
            targetNamespace="http://entities">

    <xsd:element name="security">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice maxOccurs="unbounded">
                    <xsd:element name="constraint" type="tns:constraint"
                                 minOccurs="0" maxOccurs="1"/>
                </xsd:choice>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="constraint">
        <xsd:sequence>
            <xsd:element name="url-path" type="xsd:string"/>
            <xsd:element name="role" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== BogdanDubrovniy/shop/input.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ent:security
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://entities input.xsd"
        xmlns:ent="http://entities">
    <constraint>
        <url-path>/login</url-path>
        <role>user</role>
    </constraint>

    <constraint>
        <url-path>/bucket</url-path>
        <role>unauthorized</role>
    </constraint>
    <constraint>
        <url-path>/confirm</url-path>
        <role>unauthorized</role>
    </constraint>
    <constraint>
        <url-path>/makeOrder</url-path>
        <role>unauthorized</role>
    </constraint>
</ent:security>
